### PR TITLE
Switch to CC BY-SA 4.0 International license

### PR DESCRIPTION
**Pull request by Calinou**
See https://github.com/Overv/Open.GL/pull/44.

### CODE REVIEW

**Comment by Overv** [comment]
Now for the permission from all contributors. Do you agree with changing the license?

@QuLogic @1ace @xorgy @ruslashev @Mischa-Alff @hugwijst @elmindreda @AdamNiederer @smarter @tchieze @maciejjo @timothyqiu @dustin-biser @fusijie @nathan @tronje

**Comment by tchieze** [comment]
Definitely fine with it

**Comment by smarter** [comment]
Yes, this is great!

**Comment by tronje** [comment]
Yeah, sure.

**Comment by AdamNiederer** [comment]
Sounds good!

**Comment by QuLogic** [comment]
Yep, fine by me too.

**Comment by 1ace** [comment]
:+1: I agree with the change, good idea.

**Comment by dustin-biser** [comment]
I agree with the license change.  Sounds great.

**Comment by hugwijst** [comment]
Fine by me

**Comment by Mischa-Alff** [comment]
Yup, sounds good.

**Comment by ruslashev** [comment]
Seems like a great idea

**Comment by xorgy** [comment]
:+1:

**Comment by nathan** [comment]
Agree.

**Comment by xorgy** [comment]
So far:

*Unconfirmed:*
@elmindreda
@fusijie
@maciejjo
@timothyqiu


*Confirmed:*
@1ace
@AdamNiederer
@Mischa-Alff
@QuLogic
@dustin-biser
@hugwijst
@nathan
@ruslashev
@smarter
@tchieze
@tronje
@xorgy

**Comment by maciejjo** [comment]
Agreed

**Comment by elmindreda** [comment]
__Agree__

**Comment by Overv** [comment]
Do you agree? @fusijie @timothyqiu

**Comment by timothyqiu** [comment]
Yes, that's great.

**Comment by fusijie** [comment]
It's OK.

**Comment by Overv** [comment]
Excellent.

**Pull request merged**
